#!/bin/sh

BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`

if [ ${BRANCH_NAME} == 'master' ] ; then
  echo "You cannot commit or push into master branch anymore, it has been renamed to 'main'"
  exit 1
fi